import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

function bundleStyles() {
	const parts = readdirSync('styles').filter((f) => f.endsWith('.css')).sort();
	const css = parts.map((f) => `/* ${f} */\n${readFileSync(`styles/${f}`, 'utf8').trim()}\n`).join('\n');
	writeFileSync('styles.css', css);
}

bundleStyles();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
